"""Versioned alcohol-label rulesets."""

from app.rules.prototype import (
    GOVERNMENT_WARNING_HEADING,
    GOVERNMENT_WARNING_TEXT,
    PROTOTYPE_RULESET_EFFECTIVE_DATE,
    PROTOTYPE_RULESET_ID,
    PROTOTYPE_RULESET_VERSION,
)

__all__ = [
    "GOVERNMENT_WARNING_HEADING",
    "GOVERNMENT_WARNING_TEXT",
    "PROTOTYPE_RULESET_EFFECTIVE_DATE",
    "PROTOTYPE_RULESET_ID",
    "PROTOTYPE_RULESET_VERSION",
]
