from datetime import date

PROTOTYPE_RULESET_ID = "alcohol-label-prototype"
PROTOTYPE_RULESET_VERSION = "2026-08-20"
PROTOTYPE_RULESET_EFFECTIVE_DATE = date(2026, 8, 20)

GOVERNMENT_WARNING_HEADING = "GOVERNMENT WARNING:"
GOVERNMENT_WARNING_TEXT = (
    "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT "
    "DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. "
    "(2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR "
    "OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS."
)
